#!/usr/bin/env ruby
require 'net/http'
require 'json'
full_diff =`git diff HEAD^ HEAD`
email = `git log -n 1 --format='%ae'`
email.chop!
diff = `git diff --name-status HEAD~1..HEAD`
branch = `git branch | sed -n '/\* /s///p'`
message = `git log -1 --pretty=%B`
2.times{message.chop!}
sha = `git log -1 --format='%H'`
sha.chop!
repo = `git config --get remote.origin.url`
repo = repo.chop
branch = branch.chop!
uri = URI('http://state-of-the-app.herokuapp.com/create_commit')
http = Net::HTTP.new(uri.host, uri.port)
req = Net::HTTP::Post.new(uri.path, initheader = {'Content-Type' =>'application/json'})
req.body = {commit:{sha: sha, email: email, repo: repo, diff: diff, message: message, full_diff: full_diff
}, branch:{ name: branch}}.to_json
res = http.request(req)
puts res

exit(1)
